<html>

<head>
<% ' FP_ASP -- ASP Automatically generated by a FrontPage Component. Do not Edit.
FP_CharSet = "windows-1252"
FP_CodePage = 1252 %>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<meta name="GENERATOR" content="Microsoft FrontPage 4.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>STATE</title>
<meta name="Microsoft Theme" content="none, default">
<meta name="Microsoft Border" content="none, default">
</head>

<body>

<form BOTID="0" METHOD="POST" ACTION="state.asp">
  <table BORDER="0">
    <tr>
      <td><b>STATE</b></td>
      <td><input TYPE="TEXT" NAME="STATE" VALUE="<%=Request("STATE")%>" size="20">(enter
        a two character postal abbreviation)</td>
    </tr>
  </table>
  <br>
  <input TYPE="Submit"><input TYPE="Reset"><!--webbot bot="SaveAsASP" CLIENTSIDE
  SuggestedExt="asp" PREVIEW=" " startspan --><!--webbot bot="SaveAsASP" endspan -->
  <p>&nbsp;</p>
</form>
<table border="1">
  <thead>
    <tr>
      <td><b>LAST NAME</b></td>
      <td><b>FIRST NAME</b></td>
      <td><b>STATE</b></td>
      <td><b>LIBR DAY</b></td>
      <td><b>DAYS</b></td>
      <td><b>FRI</b></td>
      <td><b>SAT</b></td>
    </tr>
  </thead>
  <tbody>
    <!--webbot bot="DatabaseRegionStart" startspan
    s-columnnames="ID,LASTNAME,FIRSTNAME,ADDRESS,CITY,STATE,ZIP_CODE,COUNTRY,LIBR_DAY,LIBR_LUNCH,X_DAYS,FRI,SAT,F_LUN,S_LUN,BANQT,SPECIAL_NE"
    s-columntypes="5,200,200,200,200,200,200,200,11,11,11,11,11,11,11,11,200"
    s-dataconnection="mailing" b-tableformat="TRUE" b-menuformat="FALSE"
    s-menuchoice="LASTNAME" s-menuvalue="LASTNAME" b-tableborder="TRUE"
    b-tableexpand="FALSE" b-tableheader="TRUE" b-listlabels="TRUE"
    b-listseparator="TRUE" i-ListFormat="0" b-makeform="TRUE"
    s-recordsource="MAILING "
    s-displaycolumns="LASTNAME,FIRSTNAME,STATE,LIBR_DAY,X_DAYS,FRI,SAT"
    s-criteria="[STATE] EQ {STATE} +" s-order="[LASTNAME] + [FIRSTNAME] +"
    s-sql="SELECT * FROM &amp;quot;MAILING &amp;quot; WHERE (STATE =  '::STATE::') ORDER BY LASTNAME ASC,FIRSTNAME ASC"
    b-procedure="FALSE" clientside SuggestedExt="asp" s-DefaultFields="STATE="
    s-NoRecordsFound="No records returned." i-MaxRecords="1000" i-GroupSize="15"
    BOTID="0" u-dblib="_fpclass/fpdblib.inc" u-dbrgn1="_fpclass/fpdbrgn1.inc"
    u-dbrgn2="_fpclass/fpdbrgn2.inc" tag="TBODY"
    local_preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; align=&quot;left&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;Database Results regions will not preview unless this page is fetched from a Web server with a web browser. The following table row will repeat once for every record returned by the query.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;"
    preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; align=&quot;left&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the start of a Database Results region. The page must be fetched from a web server with a web browser to display correctly; the current web is stored on your local disk or network.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;"
    b-WasTableFormat="TRUE" --><!--#include file="_fpclass/fpdblib.inc"-->
<%
fp_sQry="SELECT * FROM ""MAILING "" WHERE (STATE =  '::STATE::') ORDER BY LASTNAME ASC,FIRSTNAME ASC"
fp_sDefault="STATE="
fp_sNoRecords="<tr><td colspan=7 align=left width=""100%"">No records returned.</td></tr>"
fp_sDataConn="mailing"
fp_iMaxRecords=1000
fp_iCommandType=1
fp_iPageSize=15
fp_fTableFormat=True
fp_fMenuFormat=False
fp_sMenuChoice="LASTNAME"
fp_sMenuValue="LASTNAME"
fp_iDisplayCols=7
fp_fCustomQuery=False
BOTID=0
fp_iRegion=BOTID
%>
<!--#include file="_fpclass/fpdbrgn1.inc"-->
<!--webbot bot="DatabaseRegionStart" endspan -->
    <tr>
      <td><!--webbot bot="DatabaseResultColumn" startspan
        s-columnnames="ID,LASTNAME,FIRSTNAME,ADDRESS,CITY,STATE,ZIP_CODE,COUNTRY,LIBR_DAY,LIBR_LUNCH,X_DAYS,FRI,SAT,F_LUN,S_LUN,BANQT,SPECIAL_NE"
        s-column="LASTNAME" b-tableformat="TRUE" b-hasHTML="FALSE" clientside
        local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;LASTNAME&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;LASTNAME&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"LASTNAME")%><!--webbot
        bot="DatabaseResultColumn" endspan -->
      </td>
      <td><!--webbot bot="DatabaseResultColumn" startspan
        s-columnnames="ID,LASTNAME,FIRSTNAME,ADDRESS,CITY,STATE,ZIP_CODE,COUNTRY,LIBR_DAY,LIBR_LUNCH,X_DAYS,FRI,SAT,F_LUN,S_LUN,BANQT,SPECIAL_NE"
        s-column="FIRSTNAME" b-tableformat="TRUE" b-hasHTML="FALSE" clientside
        local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;FIRSTNAME&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;FIRSTNAME&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"FIRSTNAME")%><!--webbot
        bot="DatabaseResultColumn" endspan -->
      </td>
      <td><!--webbot bot="DatabaseResultColumn" startspan
        s-columnnames="ID,LASTNAME,FIRSTNAME,ADDRESS,CITY,STATE,ZIP_CODE,COUNTRY,LIBR_DAY,LIBR_LUNCH,X_DAYS,FRI,SAT,F_LUN,S_LUN,BANQT,SPECIAL_NE"
        s-column="STATE" b-tableformat="TRUE" b-hasHTML="FALSE" clientside
        local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;STATE&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;STATE&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"STATE")%><!--webbot
        bot="DatabaseResultColumn" endspan -->
      </td>
      <td><!--webbot bot="DatabaseResultColumn" startspan
        s-columnnames="ID,LASTNAME,FIRSTNAME,ADDRESS,CITY,STATE,ZIP_CODE,COUNTRY,LIBR_DAY,LIBR_LUNCH,X_DAYS,FRI,SAT,F_LUN,S_LUN,BANQT,SPECIAL_NE"
        s-column="LIBR_DAY" b-tableformat="TRUE" b-hasHTML="FALSE" clientside
        local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;LIBR_DAY&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;LIBR_DAY&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"LIBR_DAY")%><!--webbot
        bot="DatabaseResultColumn" endspan -->
      </td>
      <td><!--webbot bot="DatabaseResultColumn" startspan
        s-columnnames="ID,LASTNAME,FIRSTNAME,ADDRESS,CITY,STATE,ZIP_CODE,COUNTRY,LIBR_DAY,LIBR_LUNCH,X_DAYS,FRI,SAT,F_LUN,S_LUN,BANQT,SPECIAL_NE"
        s-column="X_DAYS" b-tableformat="TRUE" b-hasHTML="FALSE" clientside
        local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;X_DAYS&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;X_DAYS&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"X_DAYS")%><!--webbot
        bot="DatabaseResultColumn" endspan -->
      </td>
      <td><!--webbot bot="DatabaseResultColumn" startspan
        s-columnnames="ID,LASTNAME,FIRSTNAME,ADDRESS,CITY,STATE,ZIP_CODE,COUNTRY,LIBR_DAY,LIBR_LUNCH,X_DAYS,FRI,SAT,F_LUN,S_LUN,BANQT,SPECIAL_NE"
        s-column="FRI" b-tableformat="TRUE" b-hasHTML="FALSE" clientside
        local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;FRI&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;FRI&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"FRI")%><!--webbot
        bot="DatabaseResultColumn" endspan -->
      </td>
      <td><!--webbot bot="DatabaseResultColumn" startspan
        s-columnnames="ID,LASTNAME,FIRSTNAME,ADDRESS,CITY,STATE,ZIP_CODE,COUNTRY,LIBR_DAY,LIBR_LUNCH,X_DAYS,FRI,SAT,F_LUN,S_LUN,BANQT,SPECIAL_NE"
        s-column="SAT" b-tableformat="TRUE" b-hasHTML="FALSE" clientside
        local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;SAT&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;SAT&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"SAT")%><!--webbot
        bot="DatabaseResultColumn" endspan -->
      </td>
    </tr>
    <!--webbot bot="DatabaseRegionEnd" startspan b-tableformat="TRUE"
    b-menuformat="FALSE" u-dbrgn2="_fpclass/fpdbrgn2.inc" i-groupsize="15"
    clientside tag="TBODY"
    local_preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; align=&quot;left&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the end of a Database Results region.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;&lt;TR&gt;&lt;TD ALIGN=LEFT VALIGN=MIDDLE COLSPAN=64&gt;&lt;FORM&gt;&lt;NOBR&gt;&lt;INPUT TYPE=Button VALUE=&quot;  |&lt;  &quot;&gt;&lt;INPUT TYPE=Button VALUE=&quot;   &lt;  &quot;&gt;&lt;INPUT TYPE=Button VALUE=&quot;  &gt;   &quot;&gt;&lt;INPUT TYPE=Button VALUE=&quot;  &gt;|  &quot;&gt;  [1/15]&lt;/NOBR&gt;&lt;/FORM&gt;&lt;/td&gt;&lt;/tr&gt;"
    preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; align=&quot;left&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the end of a Database Results region.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;&lt;TR&gt;&lt;TD ALIGN=LEFT VALIGN=MIDDLE COLSPAN=64&gt;&lt;NOBR&gt;&lt;INPUT TYPE=Button VALUE=&quot;  |&lt;  &quot;&gt;&lt;INPUT TYPE=Button VALUE=&quot;   &lt;  &quot;&gt;&lt;INPUT TYPE=Button VALUE=&quot;  &gt;   &quot;&gt;&lt;INPUT TYPE=Button VALUE=&quot;  &gt;|  &quot;&gt;  [1/15]&lt;/NOBR&gt;&lt;BR&gt;&lt;/td&gt;&lt;/tr&gt;" --><!--#include file="_fpclass/fpdbrgn2.inc"-->
<!--webbot bot="DatabaseRegionEnd" endspan -->
  </tbody>
</table>
&nbsp;

</body>

</html>
